/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IPairNewOrder,
  IPairNewOrderInterface,
} from "../../../contracts/interface/IPairNewOrder";

const _abi = [
  {
    inputs: [],
    name: "price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token0",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "token1",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IPairNewOrder__factory {
  static readonly abi = _abi;
  static createInterface(): IPairNewOrderInterface {
    return new utils.Interface(_abi) as IPairNewOrderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IPairNewOrder {
    return new Contract(address, _abi, signerOrProvider) as IPairNewOrder;
  }
}
