/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IFactoryPair } from "./IFactoryPair";
export type { IFeeController } from "./IFeeController";
export type { IFlashLoanCallee } from "./IFlashLoanCallee";
export type { IMainValueWallet } from "./IMainValueWallet";
export type { IPairNewOrder } from "./IPairNewOrder";
export type { ISettingExchange } from "./ISettingExchange";
